### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by GuardianCosmos** [travisfoley/dfirtriage#1]
I was working on an enhancement to this which would include psexec to run it remotely by moving the files, however I keep running into errors trying to make an executable out of it, I've tried both pyinstaller 3.2 and py2exe with the single file output options, was wondering which tool you used to get everything into the one exe with only the core.ir as another dependency.

**Comment by travisfoley** [comment]
Hello, Christian,

I used pyinstaller... this is the command I ran:

pyInstaller.py -F dfirtriage.py

One thing I found was that I had to have the python script in the same
directory as pyinstaller.py.

Not sure if that would fix the compiler issues you're seeing.

Let me know.

**Comment by GuardianCosmos** [comment]
That did the trick, it wanted to be in the same directory thanks! If I get everything working right I plan to upload here and you can merge with the original if you want. Pending everything works.

**Comment by travisfoley** [comment]
Sounds great... thanks!

**Comment by travisfoley** [comment]
Resolved.
