### ISSUE TITLE
Prefetch File Integrity

### ISSUE THREAD

**Issue by Icon0clast** [travisfoley/dfirtriage#2]
Noted by one of my colleagues the prefetch files appear to lose all of their relevant data on first run, first created, etc.  We were discussing this and I brought up its not a huge deal as you can just go check the file again on the machine later if you needed to but I wanted to raise this as an issue in case you wanted to change how the prefetch files are copied.

**Comment by Icon0clast** [comment]
It looks like the fix for this would be to add the /k switch in the xcopy portion of the script, I tested this with some test files and it appears to work.

From the help file: "/K           Copies attributes. Normal Xcopy will reset read-only attributes."

**Comment by travisfoley** [comment]
Thank you for the feedback, I appreciate it.

I'll make note and fix it in the next release.
