### ISSUE TITLE
Linux machine to Windows machine remote 

### ISSUE THREAD

**Issue by sulaimanbale11** [travisfoley/dfirtriage#5]
DFIRtriage files will need to be copied to the target, then executed via remote shell. (ie. SSH or PSEXEC
Hi may you guide on how can I remote copy the files from Windows victim to Linux machine ?

Thank you

**Comment by travisfoley** [comment]
Hello!  This isn't an issue with the tool itself, but I thought this might help you figure out a solution. 
 Here's a link to 5 different ways this can be accomplished:

https://www.makeuseof.com/tag/transfer-share-files-windows-linux/

Thank you.
