### ISSUE TITLE
Can not run on windows 7 x64 because missing api-ms-win-crt-runtime-l1-1-1.dll

### ISSUE THREAD

**Issue by likekabin** [travisfoley/dfirtriage#7]
Hi my friend,
The tool is running ok on Windows 10 x64 pro, but when running on Windows 7 x64, it can not run because it missing api-ms-win-crt-runtime-l1-1-1.dll file, how can I fix this?
![image](https://user-images.githubusercontent.com/2469038/68559433-a4252480-046f-11ea-9555-abb00beaa5df.png)

Thanks.

**Comment by travisfoley** [comment]
I have not seen that issue before, I will take a look.  Thank you for letting me know.

**Comment by likekabin** [comment]
Thanks, I will wait for your research!

**Comment by travisfoley** [comment]
Did the error occur during prefetch parsing?  If not, when?

**Comment by likekabin** [comment]
error occur when the first time I run DFIRtriage.exe file, thanks!

**Comment by travisfoley** [comment]
I dropped the ball on this, I apologize. Please try the latest version and let me know if there are any issues.
