### ISSUE TITLE
Issue in running exe

### ISSUE THREAD

**Issue by michael2425** [travisfoley/dfirtriage#9]
Hi, im having the following issue when running the exe. Already run with elevated privilages

> Traceback (most recent call last):
>   File "DFIRtriage-v5-pub.py", line 903, in <module>
>   File "DFIRtriage-v5-pub.py", line 796, in fget_copy
>   File "subprocess.py", line 411, in check_output
>   File "subprocess.py", line 512, in run
> subprocess.CalledProcessError: Command 'cmd.exe /C dir /a c:\Users\"defaultuser0"\NTUSER.dat* /b ' returned non-zero exit status 1.
> [18208] Failed to execute script DFIRtriage-v5-pub

**Comment by travisfoley** [comment]
Sorry for such a late response. I need to get better and watching for comments. I just updated v5 today. Please pull the latest version and let me know if you're still having issues.

**Comment by travisfoley** [comment]
Issue should be resolved.  Please submit new issue if problems persist with latest version.
